//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentGood
    {
        public int Id { get; set; }
        public Nullable<int> IdDocument { get; set; }
        public Nullable<int> IdGood { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Good Good { get; set; }
    }
}
