//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.DocumentGood = new HashSet<DocumentGood>();
            this.Party = new HashSet<Party>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdGroupGood { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public Nullable<System.DateTime> ShelfLife { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentGood> DocumentGood { get; set; }
        public virtual GroupGood GroupGood { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Party> Party { get; set; }
    }
}
