//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public byte[] ImagePreview { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<int> IdPassport { get; set; }
        public Nullable<int> IdAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string INN { get; set; }
        public string Snils { get; set; }
        public Nullable<int> IdRole { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Role Role { get; set; }
    }
}
